---

num_rounds: 4
num_clients: 2
batch_size: 20
num_classes: 10
num_clients_per_round_fit: 2
num_clients_per_round_eval: 2
config_fit: 
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0001
  local_epochs: 3
patience: 25
output_size: 224


  
defaults:
  - strategy: fedavg
  - model: traintestpipe